version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-moderation-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web-panel:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: vapeneon-web-panel
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data      # та же БД что и у бота
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
