FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn[standard] httpx psycopg2-binary

COPY web.py .
COPY dashboard.html .
COPY favicon2.png .
COPY favicon2.ico .

CMD ["uvicorn", "web:app", "--host", "0.0.0.0", "--port", "8080"]
